version: '3.5'
services:
  iperf-service:
    #restart: unless-stopped
    build:
      context: .
    environment:
        - TZ=Europe/Paris
        #- SERVER_ENABLED=false
        - IPERF_TIME=2
    ports:
      - "8080:80"
