version: '3.5'
services:
  iperf-service:
    #restart: unless-stopped
    build:
      context: .
    environment:
        - TZ=Europe/Paris
        # - SERVER=true
        # - CLIENT=true
    ports:
      - "8080:80"
